(() => {
'use strict';
const $=id=>document.getElementById(id); const client=()=>window.LabMedSysAuth.getSupabaseClient(); let editingId=new URLSearchParams(location.search).get('id');
const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const msg=(t='',type='')=>{const e=$('professional-form-message');e.textContent=t;e.className=`professional-form-message ${type}`.trim();};
async function init(){try{const session=await window.LabMedSysAuth?.getSession?.();if(!session?.user){location.replace('index.html');return;}const name=session.user.user_metadata?.full_name||session.user.email||'Administrador',initial=name.trim().charAt(0).toUpperCase()||'A';$('workspace-user-name').textContent=name;$('dropdown-user-name').textContent=name;$('dropdown-user-email').textContent=session.user.email||'';document.querySelectorAll('.user-avatar').forEach(a=>a.textContent=initial);const menu=$('user-menu'),drop=$('user-dropdown');menu?.addEventListener('click',e=>{e.stopPropagation();const open=!drop.hidden;drop.hidden=open;menu.setAttribute('aria-expanded',String(!open));});document.addEventListener('click',()=>{if(drop&&!drop.hidden){drop.hidden=true;menu?.setAttribute('aria-expanded','false');}});drop?.addEventListener('click',e=>e.stopPropagation());$('sign-out-btn')?.addEventListener('click',async()=>{await window.LabMedSysAuth.signOut();location.replace('index.html');});
const [o,f]=await Promise.all([client().rpc('get_workspace_occupations'),client().rpc('get_workspace_professional_functions')]);if(o.error)throw o.error;if(f.error)throw f.error;$('field-occupation').innerHTML='<option value="">Selecione...</option>'+((o.data||[]).filter(x=>x.status==='active').map(x=>`<option value="${x.id}">${esc(x.name)}</option>`).join(''));$('field-function').innerHTML='<option value="">Selecione...</option>'+((f.data||[]).filter(x=>x.status==='active').map(x=>`<option value="${x.id}">${esc(x.name)}</option>`).join(''));
if(editingId){const {data,error}=await client().rpc('get_workspace_professionals');if(error)throw error;const row=(data||[]).find(x=>String(x.id)===String(editingId));if(!row)throw new Error('Profissional não encontrado.');$('page-title').textContent='Editar profissional';$('field-code').value=row.code||'';$('field-name').value=row.name||'';$('field-occupation').value=row.occupation_id||'';$('field-function').value=row.professional_function_id||'';$('field-council').value=row.council||'';$('field-registration').value=row.registration_number||'';$('field-email').value=row.email||'';$('field-phone').value=row.phone||'';}
$('professional-form').addEventListener('submit',save);$('field-code').focus();
}catch(e){console.error(e);msg(e.message||'Não foi possível carregar o cadastro.','error');}}
async function save(e){e.preventDefault();msg('');const b=$('save-btn');b.disabled=true;b.textContent='Salvando...';const p={p_code:$('field-code').value.trim(),p_name:$('field-name').value.trim(),p_occupation_id:$('field-occupation').value||null,p_professional_function_id:$('field-function').value||null,p_council:$('field-council').value.trim()||null,p_registration_number:$('field-registration').value.trim()||null,p_email:$('field-email').value.trim()||null,p_phone:$('field-phone').value.trim()||null};try{const {error}=await client().rpc(editingId?'update_workspace_professional':'create_workspace_professional',editingId?{p_id:editingId,...p}:p);if(error)throw error;location.replace('professionals.html');}catch(e){console.error(e);msg(e.message||'Não foi possível salvar o profissional.','error');b.disabled=false;b.textContent='Salvar';}}
document.addEventListener('DOMContentLoaded',init);
})();