(() => {
'use strict';
const $=id=>document.getElementById(id);const client=()=>window.LabMedSysAuth.getSupabaseClient();let rows=[];
const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const message=(text='',type='')=>{const e=$('professionals-message');e.textContent=text;e.className=`professionals-message ${type}`.trim();};
function render(){const q=$('professionals-search').value.trim().toLowerCase(),status=$('professionals-filter').value;const filtered=rows.filter(r=>(!q||[r.code,r.name,r.occupation_name,r.professional_function_name,r.registration_number].some(v=>String(v||'').toLowerCase().includes(q)))&&(status==='all'||r.status===status));$('professionals-count').textContent=`${filtered.length} ${filtered.length===1?'registro':'registros'}`;$('professionals-tbody').innerHTML=filtered.length?filtered.map(r=>`<tr><td><span class="professional-code">${esc(r.code)}</span></td><td><strong class="professional-name">${esc(r.name)}</strong></td><td>${esc(r.occupation_name||'—')}</td><td>${esc(r.professional_function_name||'—')}</td><td>${r.registration_number?`<span class="professional-registration">${esc(r.council?r.council+' · ':'')}${esc(r.registration_number)}</span>`:'—'}</td><td><span class="professional-status ${r.status}">${r.status==='active'?'Ativo':'Inativo'}</span></td><td><div class="professional-actions"><a class="professional-action" href="professional-form.html?id=${encodeURIComponent(r.id)}">Editar</a><button class="professional-action danger" data-action="status" data-id="${r.id}">${r.status==='active'?'Inativar':'Ativar'}</button></div></td></tr>`).join(''):'<tr><td colspan="7" class="professionals-empty">Nenhum profissional encontrado.</td></tr>';}
async function load(){message('Carregando...');const{data,error}=await client().rpc('get_workspace_professionals');if(error)throw error;rows=Array.isArray(data)?data:[];render();message('');}
async function changeStatus(id,status){const row=rows.find(r=>r.id===id);if(!row)return;const next=status==='active'?'inactive':'active';if(!confirm(`Deseja ${next==='inactive'?'inativar':'ativar'} ${row.name}?`))return;try{const{error}=await client().rpc('set_workspace_professional_status',{p_id:id,p_status:next});if(error)throw error;await load();message(`Profissional ${next==='active'?'ativado':'inativado'} com sucesso.`,'success');}catch(e){console.error(e);message(e.message||'Não foi possível alterar o status.','error');}}
async function init(){try{const session=await window.LabMedSysAuth?.getSession?.();if(!session?.user){location.replace('index.html');return;}const name=session.user.user_metadata?.full_name||session.user.email||'Administrador',initial=name.trim().charAt(0).toUpperCase()||'A';$('workspace-user-name').textContent=name;$('dropdown-user-name').textContent=name;$('dropdown-user-email').textContent=session.user.email||'';document.querySelectorAll('.user-avatar').forEach(a=>a.textContent=initial);const menu=$('user-menu'),drop=$('user-dropdown');menu?.addEventListener('click',e=>{e.stopPropagation();const open=!drop.hidden;drop.hidden=open;menu.setAttribute('aria-expanded',String(!open));});document.addEventListener('click',()=>{if(drop&&!drop.hidden){drop.hidden=true;menu?.setAttribute('aria-expanded','false');}});drop?.addEventListener('click',e=>e.stopPropagation());$('sign-out-btn')?.addEventListener('click',async()=>{await window.LabMedSysAuth.signOut();location.replace('index.html');});$('professionals-search')?.addEventListener('input',render);$('professionals-filter')?.addEventListener('change',render);$('professionals-tbody')?.addEventListener('click',e=>{const b=e.target.closest('[data-action="status"]');if(!b)return;const r=rows.find(x=>x.id===b.dataset.id);if(r)changeStatus(r.id,r.status);});await load();}catch(e){console.error(e);message(e.message||'Não foi possível carregar os profissionais.','error');$('professionals-tbody').innerHTML='<tr><td colspan="7" class="professionals-empty">Não foi possível carregar os dados. Verifique o acesso administrativo do Workspace.</td></tr>';}}document.addEventListener('DOMContentLoaded',init);
})();